import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google"; // Import DM Sans here
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";

// Load Geist and Geist_Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Load DM Sans font
const dmSans = DM_Sans({
  variable: "--font-dm-sans", // Set custom CSS variable for DM Sans
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
         <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} antialiased`} // Apply all fonts here
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
